# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folders', '0002_auto_20200402_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
