# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folders',
        ),
        migrations.AddField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(related_name='_folder_folders_+', to='folders.Folder'),
        ),
    ]
