# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_auto_20200402_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(blank=True, null=True, related_name='_folder_folders_+', to='folders.Folder'),
        ),
    ]
