# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-03 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0005_auto_20200402_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_folders', to='folders.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_folders', to='groups.Group'),
        ),
    ]
