# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='askedmember',
            name='username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
