# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-01 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_editor_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='permission',
            field=models.CharField(default='reader', max_length=126),
        ),
    ]
