# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='editor',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='group',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='reader',
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
