# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-31 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_files', to='folders.Folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_files', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='editor',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editor',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_files', to='files.File'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('admin', 'file')]),
        ),
    ]
