# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-05 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_last_changer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemember',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filemember',
            name='user',
        ),
        migrations.DeleteModel(
            name='FileMember',
        ),
    ]
